<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>HanumanInstitute.ApiVapourSynth</RootNamespace>
    <Description>Provides a managed interface to view VapourSynth script output in .NET</Description>
    <Product>ApiVapourSynth</Product>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HanumanInstitute.Validators" />
    <InternalsVisibleTo Include="ApiVapourSynth.Tests" />
  </ItemGroup>
</Project>
