<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>HanumanInstitute.ApiAviSynth</RootNamespace>
    <Description>Provides a managed interface to AviSynth+ script output in .NET.</Description>
    <Product>ApiAviSynth</Product>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HanumanInstitute.Validators" />
    <InternalsVisibleTo Include="ApiAviSynth.Tests" />
  </ItemGroup>
</Project>
