<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>HanumanInstitute.MediaSynthUI</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageId>MediaSynthPlayer</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="HanumanInstitute.Validators" />
    <PackageReference Include="MediaPlayer.Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ApiVapourSynth\ApiVapourSynth.csproj" />
    <ProjectReference Include="..\ApiAviSynth\ApiAviSynth.csproj" />
    <InternalsVisibleTo Include="SynthMultiViewer.Tests" />
  </ItemGroup>
</Project>
